### ISSUE TITLE
truncated responses from ask_chat

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/developer.tbd.website#666]
### Type

Docs Bug Report

### Feedback

I see truncated responses sometimes from queries like: "what does a verifiable credential look like in json?"

which results in event stream failures in browser, but I am also seeing this occasionally on server side (may be unrealted). 

Mostly so Mic follows up...

ERROR:waitress:Exception while serving /ask_chatTraceback (most recent call last):  File "/root/.local/lib/python3.9/site-packages/waitress/channel.py", line 428, in service    task.service()  File "/root/.local/lib/python3.9/site-packages/waitress/task.py", line 168, in service    self.execute()  File "/root/.local/lib/python3.9/site-packages/waitress/task.py", line 456, in execute    for chunk in app_iter:  File "/root/.local/lib/python3.9/site-packages/werkzeug/wsgi.py", line 289, in __next__    return self._next()  File "/root/.local/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded    for item in iterable:  File "/app/main.py", line 157, in stream    completion = openai.ChatCompletion.create(  File "/root/.local/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create    return super().create(*args, **kwargs)  File "/root/.local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create    response, _, api_key = requestor.request(  File "/root/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 298, in request    resp, got_stream = self._interpret_response(result, stream)  File "/root/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 700, in _interpret_response    self._interpret_response_line(  File "/root/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line    raise self.handle_error_response(openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 5266 tokens. Please reduce the length of the messages.

### Screenshots

Paste relevant images or screenshots here

**Comment by michaelneale** [comment]
upgraded the model to have up to 16K tokens when generating the answer.
