### ISSUE TITLE
[FEEDBACK]: shared-todo-completed __vite_ssr_import_2__.createMemoryHistory is not a function error

### ISSUE THREAD

**Issue by dnaicker86** [TBD54566975/developer.tbd.website#929]
### Type

Question

### Feedback

After running `pnpm install` and `pnpm run dev` the following error is displayed.

This is for the tutorials/shared-todo-completed project.

### Screenshots

Paste relevant images or screenshots here

### Relevant log output

```shell
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_2__.createMemoryHistory is not a function
  at setup (C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\pages\runtime\plugins\router.js:46:258)
  at C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\app\nuxt.js:114:60
  at fn (C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\app\nuxt.js:162:44)
  at Object.callAsync (C:\Users\denai\Github\TBD\developer.tbd.website\examples\tutorials\shared-todo-completed\unctx:68:55)
  at C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\app\nuxt.js:164:56
  at Object.runWithContext (C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\@vue+runtime-core@3.3.4\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:3855:18)    
  at callWithNuxt (C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\app\nuxt.js:164:24)  
  at Object.runWithContext (C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\app\nuxt.js:34:29)
  at applyPlugin (C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\app\nuxt.js:114:39)   
  at Module.applyPlugins (C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\app\nuxt.js:130:21)
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_2__.createMemoryHistory is not a function
  at setup (C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\pages\runtime\plugins\router.js:46:258)
  at C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\app\nuxt.js:114:60
  at fn (C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\app\nuxt.js:162:44)
  at Object.callAsync (C:\Users\denai\Github\TBD\developer.tbd.website\examples\tutorials\shared-todo-completed\unctx:68:55)
  at C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\app\nuxt.js:164:56
  at Object.runWithContext (C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\@vue+runtime-core@3.3.4\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:3855:18)    
  at callWithNuxt (C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\app\nuxt.js:164:24)  
  at Object.runWithContext (C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\app\nuxt.js:34:29)
  at applyPlugin (C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\app\nuxt.js:114:39)   
  at Module.applyPlugins (C:\Users\denai\Github\TBD\developer.tbd.website\node_modules\.pnpm\nuxt@3.7.4_@types+node@18.18.6_rollup@2.79.1_sass@1.69.4\node_modules\nuxt\dist\app\nuxt.js:130:21)
```

**Comment by ALRubinger** [comment]
Closing; not present any longer in CI
